[project]
name = "iceberg-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "ipython>=8.32.0",
    "mcp[cli]>=1.3.0",
    "pyarrow>=19.0.1",
    "pyiceberg[glue,s3fs]>=0.9.0",
]